config/routes.rb
Rails.application.routes.draw do

  root to: 'profiles#index'
  get 'comments', to: 'profiles#index'
  resources :profiles do
    resources :comments
  end
  get '/sign_in', to: 'users#sign_in'
  post '/sign_in', to: 'users#sign_in!'
  get '/sign_up', to: 'users#sign_up'
  post '/sign_up', to: 'users#sign_up!'
  get '/sign_out', to: 'users#sign_out'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :profile
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # mms: no associations?
  validates :username, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate

  private
  def authenticate
    if !session[:user]
      # mms:  What should we do if we aren't signed in?
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @profile = Profile.find(params[:profile_id])
    # mms: @profile.comments.build will associate the new comment with the profile
    @comment = Comment.new
  end

  def create
    @profile = Profile.find(params[:profile_id])
    @comment = @profile.comments.create!(comment_params)

    redirect_to profile_path(@profile)
  end

  def show
    @profile = Profile.find(params[:profile_id])
    # mms: continue to use the association, like the other actions do.
    @comment = @profile.comments.find(params[:id])
  end

  def edit
    @profile = Profile.find(params[:profile_id])
    @comment = @profile.comments.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:profile_id])
    # mms: here too.
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)

    redirect_to profile_path(@profile)
  end

  def destroy
    @profile = Profile.find(params[:profile_id])
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to profile_path(@profile)
  end
  private
  def comment_params
    params.require(:comment).permit(:full_name, :photo_url, :date_time, :content)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def index
    @profiles = Profile.all
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.create!(profile_params)

    redirect_to profiles_path(@profile)
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    @profile.update(profile_params)

    redirect_to profiles_path(@profile)
  end

  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    redirect_to profiles_path
  end

  private
  def profile_params
    params.require(:profile).permit(:full_name, :photo_url, :birth_date, :education, :about_me)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate

  def sign_up
  end

  def sign_up!
    user = User.new(
    username: params[:username],
    password_digest: BCrypt::Password.create(params[:password])
    )
    if params[:password_confirmation] != params[:password]
      message = "Passwords do not match."
    elsif user.save
      message = "Your Faithbook account has been created!"
    else
      message = "Username already in use."
    end
    redirect_to new_profile_path
    flash[:notice] = message
  end

  def sign_in
  end

  def sign_in!
    @user = User.find_by(username: params[:username])
    if !@user
      message = "No account exists with that username."
    elsif !BCrypt::Password.new(@user.password_digest).is_password?(params[:password])
      message = "Incorrect password."
    else
      message = "welcome, #{@user.username}!"
      cookies[:username] = @user.username
      # mms: recommend you only save @user.id to the session.
      # mms:    It's much smaller and contains all the info you need to find the user again:  User.find(session[:user_id])
      session[:user] = @user
    end
    redirect_to root_url
    flash[:notice] = message
  end

  def sign_out
    reset_session
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_for [@profile, @comment] do |f| %>

  <p>
    <%= f.label :full_name %>
    <%= f.text_field :full_name %>
  </p>

  <p>
    <%= f.label :photo_url %>
    <%= f.text_field :photo_url %>
  </p>

  <p>
    <%= f.label :date_time %>
    <%= f.text_field :date_time %>
  </p>

  <p>
    <%= f.label :content %>
    <%= f.text_field :content %>
  </p>

  <p>
    <%=f.submit %>
  </p>

<% end %>

app/views/comments/edit.html.erb
<div class="content">
  <h2>
    Edit your comment
  </h2>

  <%= render partial: "form" %>

  <%= link_to "Delete Comment", profile_comment_path(@profile, @comment), method: :delete, class: "delete" %>
</div>

app/views/comments/new.html.erb
<div class="content">
  <h2>
    Add a new comment
  </h2>

  <%= render partial: "form" %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Faithbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h2>fai&#10013;hbook</h2>
    <p>The Christian social network.</p>
    <nav>
      <p>
        <!-- mms: do you want to show this ALL the time, or only when we are not signed in -->
        <%= form_tag("/sign_in", method: "post") do %>
          <input type="text" name="username" placeholder="username" />
          <input type="password" name="password" placeholder="password" />
          <input type="submit" value="Sign In" />
        <% end %>
      </p>

      <a href="/">home</a> |
      <a href="/sign_up">sign up</a>
      <% if session[:user] %>
        <a href="/sign_out"> | <%= session[:user]["username"] %>:sign out</a>
      <%end%>
      <p class="notice">
        <%= flash[:notice] %>
      </p>
    </nav>
  </header>

  <main>
    <!-- mms: recommend `yield` goes here -->
  </main>

  <footer>
  </footer>
<!-- mms: This yields the contents of each view here.  Do you really want this after your footer? -->
<!-- mms:   Granted, this mistake would be more obvious if you actually had content in the footer :)  -->
<%= yield %>

</body>
</html>

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>

<p>
  <%= f.label :full_name %>
  <%= f.text_field :full_name %>
</p>

<p>
  <%= f.label :photo_url %>
  <%= f.text_field :photo_url %>
</p>

<p>
  <%= f.label :birth_date %>
  <%= f.text_field :birth_date %>
</p>

<p>
  <%= f.label :education %>
  <%= f.text_field :education %>
</p>

<p>
  <%= f.label :about_me %>
  <%= f.text_field :about_me %>
</p>

<p>
  <%=f.submit %>
</p>

<% end %>

app/views/profiles/edit.html.erb
<div class="content">
  <h2>Update your Faithbook profile</h2>
  <p>Correct your spelling errors!</p>

  <%= render partial: "form" %>

  <%= link_to "Delete Profile", profile_path(@profile), method: :delete, class: "delete" %>
</div>

app/views/profiles/index.html.erb
<div class="content">
  <p>
  Welcome to Faithbook: where you want to be when Jesus comes back.
  </p>

  <ul>

    <% @profiles.each do |profile| %>
      <li>
        <%= link_to image_tag(profile.photo_url), profile %>
        <%= link_to profile.full_name, profile %>
      </li>
    <% end %>

  </ul>

<div>
  <%= link_to "Create a faithbook profile!", "/sign_up" %> It's free, easy, and only takes a few seconds.
</div>

</div>

app/views/profiles/new.html.erb
<div class="content">
  <h2>Create a Faithbook profile!</h2>
  <p>It's super easy and only takes a few seconds.</p>

  <%= render partial: "form" %>

</div>

app/views/profiles/show.html.erb
<div class="content">
  <h2>
    <%= @profile.full_name %> <%= link_to "edit profile", edit_profile_path(@profile) %>
  </h2>
  <%= image_tag(@profile.photo_url) %>
  <p>Born:
    <%= @profile.birth_date %>
  </p>
  <p>Education:
    <%= @profile.education %>
  </p>
  <p>About <%= @profile.full_name %>:
    <%= @profile.about_me %>
  </p>
  <span id="prayer_counter">
    0
  </span> people are praying for <%= @profile.full_name %>
  <p>
    <button type="button" onclick="sendPrayer()">
      Send <%= @profile.full_name %> a prayer!
    </button>
  </p>
</div>

<div class="comments">
  <h2>
    Comments <%= link_to "add comment", new_profile_comment_path(@profile, @comment) %>
  </h2>

<ul>
  <% @profile.comments.each do |comment| %>
      <li>
        <%= comment.full_name %>
        <%= image_tag(comment.photo_url) %>
        <div class="comment_date_time">
          <%= comment.date_time %>
        </div>
        <p>
          <%= comment.content %>
        </p>
        <p>
          <%= link_to "edit comment", edit_profile_comment_path(@profile, comment) %>
        </p>
      </li>
      <% end %>
    </ul>
  </div>

app/views/users/sign_in.html.erb
<div class="content">
  <h2>Sign in</h2>

  <%= form_tag("/sign_in", method: "post") do %>
    <input type="text" name="username" placeholder="username" value="<%= cookies[:username] %>"/>
    <input type="password" name="password" placeholder="password" />
    <input type="submit" value="Sign in" />
  <% end %>

</div>

app/views/users/sign_up.html.erb
<div class="content">
  <h2>Sign up to create your Faithbook profile</h2>
  <p>It's so easy.</p>
  <%= form_tag("/sign_up", method: "post") do %>
    <input type="text" name="username" placeholder="username" />
    <input type="password" name="password" placeholder="password" />
    <input type="password" name="password_confirmation" placeholder="confirm password" />
    <input type="submit" value="Sign Up" />
  <% end %>
</div>